"""added column to car

Revision ID: 16365690b1a2
Revises: 2087d2f4ba85
Create Date: 2024-07-03 10:07:47.550742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16365690b1a2'
down_revision = '2087d2f4ba85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fleet_no', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('fleet_no')

    # ### end Alembic commands ###
