"""update db init function on app

Revision ID: 925d64877816
Revises: b2918a38844a
Create Date: 2024-07-08 15:55:30.558035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925d64877816'
down_revision = 'b2918a38844a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('chasis_no', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('LENGTH(chasis_no) = 4'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_cars_owner_id_owners')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_mechanics',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanics.id'], name=op.f('fk_owner_mechanics_mechanic_id_mechanics')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_owner_mechanics_owner_id_owners')),
    sa.PrimaryKeyConstraint('owner_id', 'mechanic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_mechanics')
    op.drop_table('cars')
    op.drop_table('users')
    op.drop_table('owners')
    op.drop_table('mechanics')
    # ### end Alembic commands ###
