"""updated the password column and included a hash method

Revision ID: b2918a38844a
Revises: d0bbab43a10e
Create Date: 2024-07-08 10:43:19.918067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2918a38844a'
down_revision = 'd0bbab43a10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('users')
    op.drop_table('mechanics')
    op.drop_table('owners')
    op.drop_table('owner_mechanics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_mechanics',
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('mechanic_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanics.id'], name='fk_owner_mechanics_mechanic_id_mechanics'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name='fk_owner_mechanics_owner_id_owners'),
    sa.PrimaryKeyConstraint('owner_id', 'mechanic_id')
    )
    op.create_table('owners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('chasis_no', sa.VARCHAR(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('LENGTH(chasis_no) = 4'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name='fk_cars_owner_id_owners'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
